"use client";

import { useEffect, useState, useRef } from "react";
import { useMessages, type Message } from "@/app/hooks/use-messages";
import { RealtimeChat } from "@/components/realtime-chat";
import { Loader2 } from "lucide-react";
import { useAuth } from "@/app/context/auth-context";
import type { RealtimeChannel } from "@supabase/supabase-js";


interface MessageViewProps {
    chatId: string;
}

export function MessageView({ chatId }: MessageViewProps) {
    const { user } = useAuth();
    const { fetchMessages, sendMessage, markMessagesAsRead, subscribeToChat, loading } = useMessages();
    const [messages, setMessages] = useState<Message[]>([]);
    const channelRef = useRef<RealtimeChannel | null>(null);
    const [isVisible, setIsVisible] = useState(false);

    useEffect(() => {
        if (chatId) {
            loadMessages();
            markMessagesAsRead(chatId);
            setIsVisible(true);

            // Subscribe to real-time updates (DB)
            channelRef.current = subscribeToChat(chatId, (message) => {
                // Determine if we should add it (deduplication happens in RealtimeChat by ID)
                // We just update the state, RealtimeChat merges it.
                setMessages((prev) => {
                    // Check if exists
                    if (prev.some(m => m.id === message.id)) return prev;
                    return [...prev, message];
                });

                // Mark as read ONLY if message is from other user AND chat is visible
                if (message.sender_id !== user?.id && isVisible) {
                    markMessagesAsRead(chatId);
                }
            });

            return () => {
                setIsVisible(false);
                if (channelRef.current) {
                    channelRef.current.unsubscribe();
                }
            };
        }
    }, [chatId, user?.id, isVisible]);

    const loadMessages = async () => {
        const data = await fetchMessages(chatId);
        setMessages(data);
    };

    const handlePersistentSend = async (chatMsg: any) => {
        // chatMsg has the ID generated by RealtimeChat
        await sendMessage(chatId, chatMsg.content, chatMsg.id);
    };

    // Map DB messages to ChatMessage format
    const mappedMessages = messages.map(msg => ({
        id: msg.id,
        content: msg.content,
        createdAt: msg.created_at,
        messageType: msg.message_type || 'text',
        recipient_id: msg.recipient_id,
        senderId: msg.sender_id,
        user: {
            name: msg.sender?.full_name || 'Unknown',
            avatarUrl: msg.sender?.profile_photo_url
        }
    }));

    // Get user details
    const userName = user?.user_metadata?.full_name || user?.email?.split('@')[0] || 'User';
    const userAvatar = user?.user_metadata?.avatar_url || user?.user_metadata?.picture;

    if (loading && messages.length === 0) {
        return (
            <div className="flex flex-col h-full items-center justify-center">
                <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
            </div>
        );
    }

    return (
        <div className="flex flex-col h-full overflow-hidden">
            <RealtimeChat
                roomName={chatId}
                username={userName}
                userAvatar={userAvatar}
                messages={mappedMessages}
                onSend={handlePersistentSend}
                currentUserId={user?.id}
            />
        </div>
    );
}

function cn(...classes: any[]) {
    return classes.filter(Boolean).join(" ");
}
